#!/bin/sh
#
# Shared shell library for test management
#
# Copyright (C) 2012, Linaro Limited.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Author: Ricardo Salveti <rsalveti@linaro.org>
#

error_msg() {
    local msg=$1
    test -z "$msg" && msg="Unknown error"
    echo "ERROR: $msg" >&2
    exit 1
}

warn_msg() {
    local msg=$1
    test -z "$msg" && msg="Unknown error"
    echo "WARNING: $msg\n" >&2
}

check_return_fail() {
    if [ $? -ne 0 ]; then
        fail_test "$1"
        return 0
    else
        return 1
    fi
}

fail_test() {
    local reason=$1
    echo "${TEST}: fail - ${reason}"
}

pass_test() {
    echo "${TEST}: pass"
}

pass_test_measure() {
    local MEASURE=$1
    local UNIT=$2
    if [ -z "$MEASURE" -o -z "$UNIT" ]; then
        echo "${TEST}: pass - 0.0 none"
    else
        echo "${TEST}: pass - $MEASURE $UNIT"
    fi
}

check_root() {
    if [ $(id -u) -eq 0 ]; then
        return 0
    else
        return 1
    fi
}

